// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: visitor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VisitorRequest_Type int32

const (
	VisitorRequest_default_type VisitorRequest_Type = 0
	VisitorRequest_api_income   VisitorRequest_Type = 1
	VisitorRequest_api_comeout  VisitorRequest_Type = 2
)

// Enum value maps for VisitorRequest_Type.
var (
	VisitorRequest_Type_name = map[int32]string{
		0: "default_type",
		1: "api_income",
		2: "api_comeout",
	}
	VisitorRequest_Type_value = map[string]int32{
		"default_type": 0,
		"api_income":   1,
		"api_comeout":  2,
	}
)

func (x VisitorRequest_Type) Enum() *VisitorRequest_Type {
	p := new(VisitorRequest_Type)
	*p = x
	return p
}

func (x VisitorRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VisitorRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_visitor_proto_enumTypes[0].Descriptor()
}

func (VisitorRequest_Type) Type() protoreflect.EnumType {
	return &file_visitor_proto_enumTypes[0]
}

func (x VisitorRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VisitorRequest_Type.Descriptor instead.
func (VisitorRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_visitor_proto_rawDescGZIP(), []int{1, 0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_visitor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_visitor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_visitor_proto_rawDescGZIP(), []int{0}
}

type VisitorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// `gorm:"primaryKey;not null;autoIncrement"`
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// `gorm:"text"`
	Request string `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Created int64  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	// `gorm:"text"`
	Response string `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	Path     string `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	// `gorm:"text"`
	Before    string              `protobuf:"bytes,6,opt,name=before,proto3" json:"before,omitempty"`
	Duration  int32               `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	Httpcode  int32               `protobuf:"varint,8,opt,name=httpcode,proto3" json:"httpcode,omitempty"`
	Type      VisitorRequest_Type `protobuf:"varint,9,opt,name=type,proto3,enum=pb.VisitorRequest_Type" json:"type,omitempty"`
	AccountId string              `protobuf:"bytes,10,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *VisitorRequest) Reset() {
	*x = VisitorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_visitor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VisitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitorRequest) ProtoMessage() {}

func (x *VisitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visitor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitorRequest.ProtoReflect.Descriptor instead.
func (*VisitorRequest) Descriptor() ([]byte, []int) {
	return file_visitor_proto_rawDescGZIP(), []int{1}
}

func (x *VisitorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VisitorRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *VisitorRequest) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *VisitorRequest) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *VisitorRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *VisitorRequest) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

func (x *VisitorRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VisitorRequest) GetHttpcode() int32 {
	if x != nil {
		return x.Httpcode
	}
	return 0
}

func (x *VisitorRequest) GetType() VisitorRequest_Type {
	if x != nil {
		return x.Type
	}
	return VisitorRequest_default_type
}

func (x *VisitorRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type Visitors struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *Visitors) Reset() {
	*x = Visitors{}
	if protoimpl.UnsafeEnabled {
		mi := &file_visitor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Visitors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Visitors) ProtoMessage() {}

func (x *Visitors) ProtoReflect() protoreflect.Message {
	mi := &file_visitor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Visitors.ProtoReflect.Descriptor instead.
func (*Visitors) Descriptor() ([]byte, []int) {
	return file_visitor_proto_rawDescGZIP(), []int{2}
}

func (x *Visitors) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_visitor_proto protoreflect.FileDescriptor

var file_visitor_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0xdb, 0x02, 0x0a,
	0x0e, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x74, 0x74, 0x70, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x68, 0x74, 0x74, 0x70, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0x39, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x61, 0x70, 0x69,
	0x5f, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x61, 0x70, 0x69,
	0x5f, 0x63, 0x6f, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x10, 0x02, 0x22, 0x20, 0x0a, 0x08, 0x56, 0x69,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x32, 0x5f, 0x0a, 0x0d,
	0x56, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a,
	0x0c, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x12, 0x2e,
	0x70, 0x62, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x73, 0x12,
	0x1c, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x21, 0x5a,
	0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x6e, 0x67,
	0x32, 0x33, 0x31, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_visitor_proto_rawDescOnce sync.Once
	file_visitor_proto_rawDescData = file_visitor_proto_rawDesc
)

func file_visitor_proto_rawDescGZIP() []byte {
	file_visitor_proto_rawDescOnce.Do(func() {
		file_visitor_proto_rawDescData = protoimpl.X.CompressGZIP(file_visitor_proto_rawDescData)
	})
	return file_visitor_proto_rawDescData
}

var file_visitor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_visitor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_visitor_proto_goTypes = []interface{}{
	(VisitorRequest_Type)(0), // 0: pb.VisitorRequest.Type
	(*Empty)(nil),            // 1: pb.Empty
	(*VisitorRequest)(nil),   // 2: pb.VisitorRequest
	(*Visitors)(nil),         // 3: pb.Visitors
}
var file_visitor_proto_depIdxs = []int32{
	0, // 0: pb.VisitorRequest.type:type_name -> pb.VisitorRequest.Type
	2, // 1: pb.VistorService.ListVisitors:input_type -> pb.VisitorRequest
	1, // 2: pb.VistorService.Ping:input_type -> pb.Empty
	3, // 3: pb.VistorService.ListVisitors:output_type -> pb.Visitors
	1, // 4: pb.VistorService.Ping:output_type -> pb.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_visitor_proto_init() }
func file_visitor_proto_init() {
	if File_visitor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_visitor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_visitor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VisitorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_visitor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Visitors); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_visitor_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_visitor_proto_goTypes,
		DependencyIndexes: file_visitor_proto_depIdxs,
		EnumInfos:         file_visitor_proto_enumTypes,
		MessageInfos:      file_visitor_proto_msgTypes,
	}.Build()
	File_visitor_proto = out.File
	file_visitor_proto_rawDesc = nil
	file_visitor_proto_goTypes = nil
	file_visitor_proto_depIdxs = nil
}
